server:
  port: 8080

  #servlet:
   # context-path: /api/
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge
    username: egt
    password: password
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      '[hibernate.format.sql]': true


